paper.pdf: paper.tex introduction.tex devito.tex compression.tex perf-revolve.tex perf-compression.tex errors-convergence.tex results-discussion.tex conclusions-futurework.tex compression.bib
	pdflatex paper.tex
	pdflatex paper.tex
	bibtex paper.aux
	pdflatex paper.tex
